# Generated by Django 5.2.7 on 2025-10-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
        ('readinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglistitem',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.news'),
        ),
    ]
