# Generated by Django 5.2.7 on 2025-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('writer', 'Writer'), ('reader', 'Reader'), ('admin', 'Admin')], default='reader', max_length=10),
        ),
    ]
