# Generated by Django 5.2.7 on 2025-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('football', 'Football'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball')], default='soccer', max_length=20),
        ),
    ]
