# Generated by Django 5.2.7 on 2025-10-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
