# Generated by Django 5.2.7 on 2025-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('soccer', 'Soccer'), ('football', 'Football'), ('hockey', 'Hockey'), ('volleyball', 'Volleyball'), ('baseball', 'Baseball')], default='update', max_length=20),
        ),
    ]
